### PR TITLE
Issue568 fix loadstac raises valueerror when utc timestamps have z as tz

### PR DESCRIPTION
**Pull request by JohanKJSchreurs**
## Issue568 fix loadstac raises valueerror when utc timestamps have z as tz 'Z': 2020-01-01T00:00:00Z

Issue: [#568](https://github.com/Open-EO/openeo-geopyspark-driver/issues/568)

PR currently in draft:
- Found a fix but haven't implemented proper test coverage yet.
- Started on the test but it is not working yet. openeo can't find the STAC file it seems. Therefore: `pytest.mark.skip`
- Still want to share it, and possible get some feedback already.

Looks like this test does need to read the STAC collection from a file. This regression test seems harder to do with mocks, because mocks typically contain the "parsed" pystac objects, not the raw data from the file. And this bug is really about different timezone formats that are allowed but that hit an edge case: Python 3.8 did not fully support the correct ISO formats yet.

An alternative solution could be to upgrade to Python 3.11 but we have to be careful when we increase the required Python version.
If we would do that, every other implementation of the openeo-python-driver may have to support 3.11. Not sure if that is a good idea.

### CODE REVIEW

**Comment by JohanKJSchreurs** [comment]
Though the PR is still in draft because this is work in progress, I requested reviewers who are working on related issues, to keep them in the know.

Nonetheless, @soxofaan and @bossie if you happen to have feedback don't hesitate to let me know.

**Review by bossie — CHANGES_REQUESTED** [review]
With a small change I managed to get the test running: https://github.com/Open-EO/openeo-geopyspark-driver/commit/bcfcec9466872daa2a327c1ddb7acf9a7f743e75

The problem is that the test runs successfully even without the fix; this is because the issue lies in the parsing of `start_datetime` and this STAC Item doesn't have one (it has a regular `datetime`, which pystac manages to parse successfully).

Instead of creating the STAC Collection in code and saving it to disk, I would just do like the other tests and add regular JSON files to the repo. That way:
- it makes it immediately clear what your STAC looks like;
- you don't depend on the way pystac renders your UTC timestamps in the first place (does it actually render the time zone as 'Z' or e.g. '+00:00'?).

For an example STAC Item with `start_datetime`/`end_datetime` you might want to copy an existing one and adapt e.g. from https://vlcc.geoville.com/resto/collections/BVL_v1/items; this particular collection is conveniently one that we actually want to support.

As for the fix itself: instead of first trying with `datetime.fromisoformat`, then falling back to `rfc3339.parse`, maybe try a more lenient parser that supports both 'Z' and timezone offsets like `dateutil.parser.parse` (python-dateutil is already a dependency).

**Comment by soxofaan** [comment]
> As for the fix itself: instead of first trying with datetime.fromisoformat, then falling back to rfc3339.parse, maybe try a more lenient parser that supports both 'Z' and timezone offsets like dateutil.parser.parse (python-dateutil is already a dependency).

Indeed, I would also prefer a generic solution like that over adhoc and version dependent try-except constructs.
Also note that rfc3339 from the python client is primarily intended as a best effort date (re)formatter, while super robust date parsing is not its main focus.

**Comment by JohanKJSchreurs** [comment]
Closing this PR: it is no longer needed because @bossie was able to fix this already in https://github.com/Open-EO/openeo-geopyspark-driver/pull/673.

**Pull request closed without merging**
