### PR TITLE
Change max_executor_or_driver_memory to 16. 64 was a very high limit

### PR DESCRIPTION
**Pull request by EmileSonneveld**

### CODE REVIEW

**Comment by tcassaert** [comment]
Is this 16GB a combination of overhead and "regular" memory?

**Comment by EmileSonneveld** [comment]
@tcassaert It goes through tests. Is the limit fine, or too low? I often specified 20Gb `driver-memory` in the past, so I got the feeling there is space for more

**Comment by jdries** [comment]
Pay attention that things depend on the environment. Terrascope has higher limits, cdse limit is 15GB....
________________________________

**Comment by tcassaert** [comment]
@EmileSonneveld for CDSE the limit the user sees should then be 15GB instead of 16GB.

**Comment by jdries** [comment]
Config adjusted in the right place, closing this one.

**Pull request closed without merging**
